### ISSUE TITLE
Can't get rid of --autoDetect

### ISSUE THREAD

**Issue by maaattes** [Konfekt/vim-langtool#2]
No matter what I set `let b:langtool_parameters`,  `let g:langtool_parameters` or `set spelllang` to, `languagetool-commandline.jar` always executes with `--autoDetect`. How can I avoid that? :(

**Comment by Konfekt** [comment]
Strange. The lines

```vim
" compiler/langtool.vim (lines 23-26)
if !exists('b:langtool_parameters')
  let b:langtool_lang = matchstr(&l:spelllang, '^\a\a')
  let b:langtool_parameters = empty(b:langtool_lang) ? '--autoDetect' : '--language ' . b:langtool_lang
endif
```

should pick up the value of `&spelllang`.

Other than that, the autocmd triggers

```vim
autocmd OptionSet spelllang let b:langtool_parameters = '--language ' . v:option_new 
autocmd BufWinEnter * let b:langtool_parameters = '--language  ' . &spelllang 
```

should achieve this.

**Comment by Konfekt** [comment]
If you use `:LangTool`, then 

```vim
  " use spelllang to set lang of langtool
  if &l:spell && !empty(&l:spelllang)
    let lang = s:lang(&l:spelllang)
    if !empty(lang)
      let b:langtool_parameters = '--language ' . lang
    endif
  else
    echohl WarningMsg | echomsg "Please set spellllang for more accurate check by LanguageTool. Using autodetection instead." | echohl None
    let b:langtool_parameters = '--autoDetect'
  endif
```

should even issue a warning when `autoDetect` is used.

**Comment by maaattes** [comment]
Ah, okay. I also have to use `set spell`. Not only `set spelllang=de`. Now it seems to work.
But I can't find the results. When I execute `:LangTool` I only see:
```
|| [java -jar '/home/mattes/.vim/LanguageTool/languagetool-commandline.jar'  --language de]
|| Working on STDIN...
|| [Finished in 7 seconds]
```
in the quickfix list. There is no location list. Whereas the command `java -jar /home/mattes/.vim/LanguageTool/languagetool-commandline.jar -l de-DE test.txt` produces the expected output. Excuse my ignorance, but I've never used LanguageTool for spell checking until now.

**Comment by Konfekt** [comment]
I will disable the check for spell check.

I cannot reproduce. I am using `Asyncrun` with `LanguageTool version 4.9-SNAPSHOT (2020-03-06 19:46, 7f75341)` and today's snapshot `LanguageTool version 5.1-SNAPSHOT (2020-09-08 18:50, c51677c)` on

```
VIM - Vi IMproved 8.0 (2016 Sep 12)
Patch incluse: 1-1568
Compilato da 'http://www.opensuse.org/'
```

**Comment by Konfekt** [comment]
> But I can't find the results. When I execute `:LangTool` I only see:
> 
> ```
> || [java -jar '/home/mattes/.vim/LanguageTool/languagetool-commandline.jar'  --language de]
> || Working on STDIN...
> || [Finished in 7 seconds]
> ```
> 
> in the quickfix list. There is no location list. Whereas the command `java -jar /home/mattes/.vim/LanguageTool/languagetool-commandline.jar -l de-DE test.txt` produces the expected output.

What goes wrong is that no file path is given after the command, though

```vim
" autoload/langtool.vim (line 56)
exe 'silent ' . (exists(':Make') == 2 ? 'Make' : 'lmake') . a:bang . ' ' . shellescape(expand('%'))
```

passes it. `:LangTool` saves the buffer if need be. Therefore I am wondering why standard input is assumed instead.

**Comment by maaattes** [comment]
> I will disable the check for spell check.
> 
> I cannot reproduce. I am using `Asyncrun` with `LanguageTool version 4.9-SNAPSHOT (2020-03-06 19:46, 7f75341)` and today's snapshot `LanguageTool version 5.1-SNAPSHOT (2020-09-08 18:50, c51677c)` on
> 
> ```
> VIM - Vi IMproved 8.0 (2016 Sep 12)
> Patch incluse: 1-1568
> Compilato da 'http://www.opensuse.org/'
> ```

Okay, I'm using `LanguageTool version 5.0 (2020-06-26 21:36, cee311a)` on
```
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Aug 31 2020 00:00:00)
Inklusive der Patches: 1-1551
Verändert von <bugzilla@redhat.com>
Übersetzt von <bugzilla@redhat.com>
```
Using latest snapshot of `LanguageTool` doesn't make a difference.

> What goes wrong is that no file path is given after the command, though

Yeah, I've noticed that too. Don't know why though. For testing purpose I'm using this `minimal.vim`:
```vim
if &compatible
  set nocompatible
endif

filetype plugin indent on
set spelllang=de

if exists('*minpac#init')
    call minpac#init()
    call minpac#add('k-takata/minpac', {'type': 'opt'})
    call minpac#add('Konfekt/vim-langtool')
    call minpac#add('skywind3000/asyncrun.vim')
endif

let g:langtool_jar = '~/.vim/LanguageTool/languagetool-commandline.jar'
let g:asyncrun_trim = 1
command! -bang -nargs=* -complete=file Make AsyncRun<bang> -auto=make -program=make

autocmd QuickFixCmdPost make cwindow
```

**Comment by Konfekt** [comment]
Thank you, now it is reproducible. Mea culpa, I forgot passing the arguments, in particular the file name, to the Make command when giving its definition in the doc: It should be:

```vim
    command! -bang -nargs=* -complete=file Make AsyncRun<bang> -auto=make -program=make -strip <args>
```

instead. Now it works.
